### PR TITLE
Run update script, get rid of import/export bridge, and make sure v2 is always used

### PR DESCRIPTION
**Pull request by jeskew**
The new endpoints.json file indicates that SimpleDB supports SigV4, but this is not accurate. Most of this PR is just noise from running `make update` and pulling down new test classes; the fix is just on https://github.com/aws/aws-sdk-php-v3-bridge/compare/feature/support-3.18.7-and-above?expand=1#diff-0f065fdd7a16baa81939b6a369e77cffR28

I also removed Import/Export, as the new endpoints.json file found a way to use SigV4 with that service.

/cc @cjyclaire

### CODE REVIEW

**Comment by cjyclaire** [comment]
Cool, I was also thinking about removing ImportExport since we already support that in SDK, so, thanks!
Looks good to me.

**Comment by cjyclaire** [comment]
Maybe `ImportExport` could be removed from README.md as well before we ship this.

**Comment by jeskew** [comment]
Good catch. I've added a commit to update the readme as well.

**Comment by cjyclaire** [comment]
Sweet! Now :shipit:

**Pull request merged**
